module.exports = {
  google: {
    analytics: {
      TRACKING_ID: 'UA-XXXXXXXX-X'
    },
    recaptcha: {
      SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      CLIENT_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-wZdWSMJ4rXi6UjoLofi'
    },
    contact_form: {
      CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXX',
      CLIENT_ID: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      REDIRECT_URIS: ['https://developers.google.com/oauthplayground'],
      USER: 'admin@example.com',
      RECIPIENT: 'recipient@example.com',
      REFRESH_TOKEN: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    }
  }
}
